apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
   env: prod
bases:
- ../base
namePrefix: prod-

replicas:
- name: demoapp02-deployment
  count: 3

patches:
- target:
    kind: Ingress
    name: demoapp02-ingress
  path: ingress-patch.yml  


images:
- name: demoapp02
  newName: 050400155701.dkr.ecr.us-east-1.amazonaws.com/marcin-cicd-demo
  newTag: 241f178