apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
resources:
- ../base
namePrefix: dev-
replicas:
- name: busybox-deployment
  count: 4
images:
- name: busybox
  newTag: "1.35"