apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prd
resources:
- ../base
namePrefix: prod-
replicas:
- name: busybox-deployment
  count: 1
images:
- name: busybox
  newTag: "1.35"