apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prd
resources:
- ../base
namePrefix: prod-
replicas:
- name: nginx-deployment
  count: 1
images:
- name: nginx
  newTag: 1.13.2
 